ruby '2.6.6'
source 'https://rubygems.org'

gem 'saml_idp'
gem 'sinatra'
gem 'sinatra_more', require: 'sinatra_more/markup_plugin'
gem 'xmlenc'

group :development, :test do
  gem 'dotenv'
  gem 'pry'
end